### ISSUE TITLE
URGENT: form doesn't work

### ISSUE THREAD

**Issue by sandblasta** [paulinagua/COMD-2451-Final-Project-Website#1]
Hi Paulina,

Your contact form doesn't work on your website right now.

Fixing it now will allow me to give you points on your final project and also 100% on your week 11 HW .

all you have to do is 
1. check your email and copy the "random-like string" from that email, paste it in place of your email address. 
2. Then upload the updated contact.html to gitHub, 
3. Go back to the email and push the blue "activate form" button

This evening is the Last chance b/c of the deadline! Please do it now!

Best,

Prof. L

**Comment by paulinagua** [comment]
Hi professor, I activated the form again and tested it to see that it works now. Please let me know if it works on your end as well.
